<a href="https://colab.research.google.com/github/Luthfi-BTJ/Data-Wrangling-Cleaning/blob/main/indonesia_covid19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [177]:
import pandas as pd

# Load Dataset

In [178]:
covid = pd.read_csv('/content/covid_19_indonesia_time_series_all.csv')
covid

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.00,1.00
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31817,9/15/2022,ID-SA,Sulawesi Utara,37,0,0,37,52770,1213,50997,...,1.259638,14.01,19974.38,0.0,459.14,45.91,2.30%,96.64%,2.85,1.00
31818,9/15/2022,ID-SB,Sumatera Barat,13,0,3,10,104640,2371,102066,...,-0.850253,2.36,18959.11,0.0,429.59,42.96,2.27%,97.54%,6.50,1.00
31819,9/15/2022,ID-SS,Sumatera Selatan,16,0,1,15,82198,3376,78510,...,-3.216212,1.95,10002.74,0.0,410.83,41.08,4.11%,95.51%,3.20,1.00
31820,9/15/2022,ID-SU,Sumatera Utara,50,0,5,45,158866,3288,154924,...,2.191894,3.36,10680.15,0.0,221.04,22.10,2.07%,97.52%,1.92,1.00
31821,9/16/2022,IDN,Indonesia,2358,27,2997,-666,6405044,157876,6218708,...,-0.789275,8.89,24153.07,0.1,595.34,59.53,2.46%,97.09%,0.89,1.29

In [179]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         31822 non-null  object
 1   Location ISO Code            31822 non-null  object
 2   Location                     31822 non-null  object
 3   New Cases                    31822 non-null  int64
 4   New Deaths                   31822 non-null  int64
 5   New Recovered                31822 non-null  int64
 6   New Active Cases             31822 non-null  int64
 7   Total Cases                  31822 non-null  int64
 8   Total Deaths                 31822 non-null  int64
 9   Total Recovered              31822 non-null  int64
 10  Total Active Cases           31822 non-null  int64
 11  Location Level               31822 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     30893 non-null  object
 14  Country                      31822 non-null  object
 15  Continent                    31822 non-null  object
 16  Island                       30893 non-null  object
 17  Time Zone                    30893 non-null  object
 18  Special Status               4558 non-null   object
 19  Total Regencies              31822 non-null  int64
 20  Total Cities                 30921 non-null  float64
 21  Total Districts              31822 non-null  int64
 22  Total Urban Villages         30918 non-null  float64
 23  Total Rural Villages         30893 non-null  float64
 24  Area (km2)                   31822 non-null  int64
 25  Population                   31822 non-null  int64
 26  Population Density           31822 non-null  float64
 27  Longitude                    31822 non-null  float64
 28  Latitude                     31822 non-null  float64
 29  New Cases per Million        31822 non-null  float64
 30  Total Cases per Million      31822 non-null  float64
 31  New Deaths per Million       31822 non-null  float64
 32  Total Deaths per Million     31822 non-null  float64
 33  Total Deaths per 100rb       31822 non-null  float64
 34  Case Fatality Rate           31822 non-null  object
 35  Case Recovered Rate          31822 non-null  object
 36  Growth Factor of New Cases   29883 non-null  float64
 37  Growth Factor of New Deaths  28375 non-null  float64
dtypes: float64(14), int64(12), object(12)
memory usage: 9.2+ MB

# Cleaning Data

Drop Duplicate

In [180]:
covid = covid.drop_duplicates()
covid

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.00,1.00
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31817,9/15/2022,ID-SA,Sulawesi Utara,37,0,0,37,52770,1213,50997,...,1.259638,14.01,19974.38,0.0,459.14,45.91,2.30%,96.64%,2.85,1.00
31818,9/15/2022,ID-SB,Sumatera Barat,13,0,3,10,104640,2371,102066,...,-0.850253,2.36,18959.11,0.0,429.59,42.96,2.27%,97.54%,6.50,1.00
31819,9/15/2022,ID-SS,Sumatera Selatan,16,0,1,15,82198,3376,78510,...,-3.216212,1.95,10002.74,0.0,410.83,41.08,4.11%,95.51%,3.20,1.00
31820,9/15/2022,ID-SU,Sumatera Utara,50,0,5,45,158866,3288,154924,...,2.191894,3.36,10680.15,0.0,221.04,22.10,2.07%,97.52%,1.92,1.00
31821,9/16/2022,IDN,Indonesia,2358,27,2997,-666,6405044,157876,6218708,...,-0.789275,8.89,24153.07,0.1,595.34,59.53,2.46%,97.09%,0.89,1.29

Drop 'City or Regency' and 'Special Status' Columns

In [181]:
covid = covid.drop(['City or Regency', 'Special Status'], axis=1)
covid

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.00,1.00
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31817,9/15/2022,ID-SA,Sulawesi Utara,37,0,0,37,52770,1213,50997,...,1.259638,14.01,19974.38,0.0,459.14,45.91,2.30%,96.64%,2.85,1.00
31818,9/15/2022,ID-SB,Sumatera Barat,13,0,3,10,104640,2371,102066,...,-0.850253,2.36,18959.11,0.0,429.59,42.96,2.27%,97.54%,6.50,1.00
31819,9/15/2022,ID-SS,Sumatera Selatan,16,0,1,15,82198,3376,78510,...,-3.216212,1.95,10002.74,0.0,410.83,41.08,4.11%,95.51%,3.20,1.00
31820,9/15/2022,ID-SU,Sumatera Utara,50,0,5,45,158866,3288,154924,...,2.191894,3.36,10680.15,0.0,221.04,22.10,2.07%,97.52%,1.92,1.00
31821,9/16/2022,IDN,Indonesia,2358,27,2997,-666,6405044,157876,6218708,...,-0.789275,8.89,24153.07,0.1,595.34,59.53,2.46%,97.09%,0.89,1.29

Turn "Date" Column into Date Data Type

In [182]:
covid['Date'] = pd.to_datetime(covid['Date'])
covid['Date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 31822 entries, 0 to 31821
Series name: Date
Non-Null Count  Dtype
--------------  -----
31822 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 248.7 KB

Change 'Case Fatality Rate' and 'Case Recovered Rate' into numeric and remove the "%"

In [183]:
# Check the column
covid[['Case Fatality Rate', 'Case Recovered Rate']]

      Case Fatality Rate Case Recovered Rate
0                 51.28%             192.31%
1                 48.78%             182.93%
2                  0.00%               0.00%
3                  0.00%             100.00%
4                 46.51%             174.42%
...                  ...                 ...
31817              2.30%              96.64%
31818              2.27%              97.54%
31819              4.11%              95.51%
31820              2.07%              97.52%
31821              2.46%              97.09%

[31822 rows x 2 columns]

In [184]:
# Remove the "%" and turned it into numeric value
col_rate = ['Case Fatality Rate', 'Case Recovered Rate']
for i in col_rate:
  covid[i] = pd.to_numeric(covid[i].map(lambda x: x.rstrip('%')))
covid

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,2020-03-01,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28,192.31,NaN,NaN
1,2020-03-02,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78,182.93,1.00,1.00
2,2020-03-02,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00,0.00,NaN,NaN
3,2020-03-02,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00,100.00,NaN,NaN
4,2020-03-03,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51,174.42,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31817,2022-09-15,ID-SA,Sulawesi Utara,37,0,0,37,52770,1213,50997,...,1.259638,14.01,19974.38,0.0,459.14,45.91,2.30,96.64,2.85,1.00
31818,2022-09-15,ID-SB,Sumatera Barat,13,0,3,10,104640,2371,102066,...,-0.850253,2.36,18959.11,0.0,429.59,42.96,2.27,97.54,6.50,1.00
31819,2022-09-15,ID-SS,Sumatera Selatan,16,0,1,15,82198,3376,78510,...,-3.216212,1.95,10002.74,0.0,410.83,41.08,4.11,95.51,3.20,1.00
31820,2022-09-15,ID-SU,Sumatera Utara,50,0,5,45,158866,3288,154924,...,2.191894,3.36,10680.15,0.0,221.04,22.10,2.07,97.52,1.92,1.00
31821,2022-09-16,IDN,Indonesia,2358,27,2997,-666,6405044,157876,6218708,...,-0.789275,8.89,24153.07,0.1,595.34,59.53,2.46,97.09,0.89,1.29

Handle Outlier Values for 'Case Recovered Rate' and 'Case Fatality Rate'

In [185]:
# Check how much 'Case Recovered Rate' that exceed 100%
covid['Case Recovered Rate'][covid['Case Recovered Rate'] > 100].count()

np.int64(288)

In [186]:
covid.loc[(covid['Case Recovered Rate'] > 100), 'Case Recovered Rate'] = 100
covid['Case Recovered Rate']

0        100.00
1        100.00
2          0.00
3        100.00
4        100.00
          ...
31817     96.64
31818     97.54
31819     95.51
31820     97.52
31821     97.09
Name: Case Recovered Rate, Length: 31822, dtype: float64

In [187]:
# Check how much 'Case Fatality Rate' that exceed 100%
covid['Case Fatality Rate'][covid['Case Fatality Rate'] > 100].count()

np.int64(43)

In [188]:
covid.loc[(covid['Case Recovered Rate'] > 100), 'Case Recovered Rate'] = 100
covid['Case Recovered Rate']

0        100.00
1        100.00
2          0.00
3        100.00
4        100.00
          ...
31817     96.64
31818     97.54
31819     95.51
31820     97.52
31821     97.09
Name: Case Recovered Rate, Length: 31822, dtype: float64

In [189]:
covid[['Case Fatality Rate', 'Case Recovered Rate']]

       Case Fatality Rate  Case Recovered Rate
0                   51.28               100.00
1                   48.78               100.00
2                    0.00                 0.00
3                    0.00               100.00
4                   46.51               100.00
...                   ...                  ...
31817                2.30                96.64
31818                2.27                97.54
31819                4.11                95.51
31820                2.07                97.52
31821                2.46                97.09

[31822 rows x 2 columns]

Change Every Null Value

In [190]:
# Change all NaN values in 'Time Zone' into UTC+07:00
covid['Time Zone'] = covid['Time Zone'].fillna('UTC+07:00')
covid['Time Zone'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 31822 entries, 0 to 31821
Series name: Time Zone
Non-Null Count  Dtype
--------------  -----
31822 non-null  object
dtypes: object(1)
memory usage: 248.7+ KB

In [191]:
# Change all NaN values in 'Province' and 'Island' into Indonesia
covid['Province'] = covid['Province'].fillna('Indonesia')
covid['Island'] = covid['Island'].fillna('Indonesia')
covid[['Province','Island']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Province  31822 non-null  object
 1   Island    31822 non-null  object
dtypes: object(2)
memory usage: 497.3+ KB

In [192]:
# Change all NaN in 'Total Cities', 'Growth Factor of New Cases', and 'Growth Factor of New Deaths' with mean of each their own column
col_mean = ['Total Cities','Growth Factor of New Cases','Growth Factor of New Deaths']
for i in col_mean:
  covid[i] = covid[i].fillna(covid[i].mean())
covid[col_mean].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Total Cities                 31822 non-null  float64
 1   Growth Factor of New Cases   31822 non-null  float64
 2   Growth Factor of New Deaths  31822 non-null  float64
dtypes: float64(3)
memory usage: 746.0 KB

In [193]:
# Change all NaN in 'Total Urban Villages' and 'Total Rural Villages' with 0
covid['Total Urban Villages'] = covid['Total Urban Villages'].fillna(0)
covid['Total Rural Villages'] = covid['Total Rural Villages'].fillna(0)
covid[['Total Urban Villages','Total Rural Villages']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Total Urban Villages  31822 non-null  float64
 1   Total Rural Villages  31822 non-null  float64
dtypes: float64(2)
memory usage: 497.3 KB

# Validation

In [194]:
# 1. Basic Info
print("Basic info:")
covid.info()

Basic info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         31822 non-null  datetime64[ns]
 1   Location ISO Code            31822 non-null  object
 2   Location                     31822 non-null  object
 3   New Cases                    31822 non-null  int64
 4   New Deaths                   31822 non-null  int64
 5   New Recovered                31822 non-null  int64
 6   New Active Cases             31822 non-null  int64
 7   Total Cases                  31822 non-null  int64
 8   Total Deaths                 31822 non-null  int64
 9   Total Recovered              31822 non-null  int64
 10  Total Active Cases           31822 non-null  int64
 11  Location Level               31822 non-null  object
 12  Province                     31822 non-null  object
 13  Country                      31822 non-null  object
 14  Continent                    31822 non-null  object
 15  Island                       31822 non-null  object
 16  Time Zone                    31822 non-null  object
 17  Total Regencies              31822 non-null  int64
 18  Total Cities                 31822 non-null  float64
 19  Total Districts              31822 non-null  int64
 20  Total Urban Villages         31822 non-null  float64
 21  Total Rural Villages         31822 non-null  float64
 22  Area (km2)                   31822 non-null  int64
 23  Population                   31822 non-null  int64
 24  Population Density           31822 non-null  float64
 25  Longitude                    31822 non-null  float64
 26  Latitude                     31822 non-null  float64
 27  New Cases per Million        31822 non-null  float64
 28  Total Cases per Million      31822 non-null  float64
 29  New Deaths per Million       31822 non-null  float64
 30  Total Deaths per Million     31822 non-null  float64
 31  Total Deaths per 100rb       31822 non-null  float64
 32  Case Fatality Rate           31822 non-null  float64
 33  Case Recovered Rate          31822 non-null  float64
 34  Growth Factor of New Cases   31822 non-null  float64
 35  Growth Factor of New Deaths  31822 non-null  float64
dtypes: datetime64[ns](1), float64(15), int64(12), object(8)
memory usage: 8.7+ MB

In [195]:
# 2. Check for missing values
print("Missing values:")
print(covid.isnull().sum())

Missing values:
Date                           0
Location ISO Code              0
Location                       0
New Cases                      0
New Deaths                     0
New Recovered                  0
New Active Cases               0
Total Cases                    0
Total Deaths                   0
Total Recovered                0
Total Active Cases             0
Location Level                 0
Province                       0
Country                        0
Continent                      0
Island                         0
Time Zone                      0
Total Regencies                0
Total Cities                   0
Total Districts                0
Total Urban Villages           0
Total Rural Villages           0
Area (km2)                     0
Population                     0
Population Density             0
Longitude                      0
Latitude                       0
New Cases per Million          0
Total Cases per Million        0
New Deaths per Million         0
Total Deaths per Million       0
Total Deaths per 100rb         0
Case Fatality Rate             0
Case Recovered Rate            0
Growth Factor of New Cases     0
Growth Factor of New Deaths    0
dtype: int64

In [196]:
# 3. Check for duplicates
print(f"Duplicate rows in covid: {covid.duplicated().sum()}")

Duplicate rows in df: 0